- hosts: localhost
  become: yes
  vars:
    minikube_version: '1.10.1'
    username: vagrant
  roles:
    - role: ericsysmin.docker.docker
    - role: robertdebock.bootstrap
    - role: robertdebock.kubectl
    - role: gantsign.minikube
  tasks:

    - name: Garante que o {{ username }} esteja no grupo docker
      user:
        name: "{{ username }}"
        groups: docker

    - name: Reset ssh connection
      meta: reset_connection

    - name: Inicia o minikube
      shell: minikube start --driver=docker
      become: no
